### ISSUE TITLE
[HW1] Get points for Wrong number of lines

### ISSUE THREAD

**Issue by ivanvoid** [yungyuc/nsdhw_21sp#11]
Hi I get points for wrong number of lines using `wc -l < $1` but when I use `grep -c ^ $1` (where ^ stands for start of a line) I get right answer but don't get points. I will submit version that get points, but will leave grep version in a comments. Check this out please.  
![image](https://user-images.githubusercontent.com/59028817/110194977-85257f80-7e76-11eb-9005-3854b7cdb375.png)
![image](https://user-images.githubusercontent.com/59028817/110194982-91a9d800-7e76-11eb-92ab-1461f94244c2.png)
![image](https://user-images.githubusercontent.com/59028817/110194988-9a9aa980-7e76-11eb-9e27-467150f07a60.png)
![image](https://user-images.githubusercontent.com/59028817/110194997-a2f2e480-7e76-11eb-8353-168e5928faba.png)

**Comment by yungyuc** [comment]
Post images for code is never a good idea.  Please make it something that others can copy and search, e.g.,

```console
$ ../validate.sh
```

Check https://guides.github.com/features/mastering-markdown/.

The point of this homework assignment is for you to get familar with scripting.  It is intentional to use a tight criteria.  To request for change of golden it is not sufficient to give an alternate implmentation incompatible to the criteria set in the validation script.  Please point out what change needs to be made in the validator and why the change should be preferred.  PRs are welcome.
